# Generated by Django 5.1.3 on 2024-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pal', '0002_alter_task_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('in_between', 'In Between'), ('completed', 'Completed')], default='NA', max_length=20),
        ),
    ]
